### ISSUE TITLE
Build Database

### ISSUE THREAD

**Issue by chrstphrclmn** [1908-aug19-java/Project2-Samuel-Chris-Kyle-BackEnd#1]
Use Spring to build the DB, do as you see fit.

**Comment by watchdogoblivion** [comment]
# __*Main concern*__
The database is created using hibernate mappings in the DAO's. I did not have to manually go into postgres. There was a big compatibility issue with spring boot. If you create a new spring boot application using "Spring io intializr", then it uses the most recent versions of spring. When creating a standard web application, the setup used is a dynamic web module. Normally this version can be modified. Spring boot sets the version explicitly to 4.0. You can technically change this by first going to the navigator, opening up the .settings folder and modifying org.eclipse.wst.common.project.facet.core.xml to have the version set to what you wish. Then going to properties, project facets and setting it there in case it does not update. However, with the new versions of spring boot, once you run maven update, it will automatically override those settings. This was not the case with older spring versions. This is also currently a problem because anything lower than tomcat 9 does not support Dynamic module version 4.0. Since AWS does not currently provide support for tomcat 9,I had to change the spring version which required a slight modification of the project structure.

## Overall Additions 
_Additions are placed in the order they were worked on._ 
1. Added the expected DAO objects, and the rest controller, service, and repository (not JPA) for the Role and User. 
1. Added custom error handling. 
1. Added Postman collection for testing role controller endpoints. 
1. Setup hibernate config file for database CRUD. 
1. Added logging. 
1. Added a custom query builder.
1. Added entity details for entity information which is a centralized location to modify entity details.
1. Added DTO layer for frontend to backend object scalability and proper practice. Modified controllers to reflect the change. 
1. Completed migration from hibernate to spring jpa. 
1. Added properties files for credentials and additional configuration. 
1. Added data.ql for initial CRUD. 
1. Added detail utils for name conversion of table column names to dao field names. 
1. Implemented JpaSpecificationExecutor for custom query manipulation. 
1. Modified DTO's, DAO's and Details to reflect the relationship with account. 
1. Added data.sql for base inserts. 
1. Added Account repo and skeleton for account service and controller. 
1. Tested three main endpoints user, account, role. 
1. ### _**Completed Base Database Build with Account, User, and Role**_
1. Added custom validations for each endpoint. 
1. Added endpoint descriptions in README. 
1. Refactored Exception manager. 
1. Added Aspect for logging exceptions.
1. Removed querybuilder. 
1. Added security handler for encryption, hashing, and jwt. Security is not implemented yet.

**Comment by watchdogoblivion** [comment]
The official final commit on this was 14712e6d0b03f2a4516ef0f2b75750739e88a14b and it was for feature branch "feature_springdatabase".
